services:
  # 1. Aplicação Spring Boot
  backend:
    build: .
    container_name: user_system_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      # Sobrescreve a config do application.yml para rodar dentro da rede Docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/usermanagement
    restart: always

  # 2. Banco de Dados
  postgres:
    image: postgres:16-alpine
    container_name: user_system_db
    environment:
      POSTGRES_DB: usermanagement
      POSTGRES_USER: jonas
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432" # Exposto para você acessar via IDE também
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # 3. Interface Visual do Banco
  pgadmin:
    image: dpage/pgadmin4
    container_name: user_system_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data: